### PR TITLE
Added functionality to disable scrolling when modal is opened

### PR DESCRIPTION
**Pull request by idChef**
Fixing issue #28 
Tested on chrome and mobile safari

### CODE REVIEW

**Comment by flekschas** [comment]
Thank you for the PR.

Somehow the build script fails. Can you take a look at fix the issue? Thanks.

It would also be great if you could provide a live demo. The easiest way is to just clone https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4?version=3.20.1. This way we can quickly test it in other browsers beyond Chrome and Mobile Safari.

**Comment by idChef** [comment]
Sorry,  I wasn't familar with terminating Javascript Functions with semicolons. Here is the live demo you were asking for https://svelte.dev/repl/03d4b30556014a449b542194aab711f1?version=3.20.1

**Comment by flekschas** [comment]
Thanks for the demo!

We require the semicolon for all kind of expressions, including function expression. Function declarations don't need a semicolon though :)

The PR looks good. However, I just found a bug, which I have to investigate. When you first open up the modal with the customized styles and then try to open up the modal triggered by the button at the very end of the page, the modal is halfway cut off.

Mar-27-2021 21-30-56


The issue is probably unrelated to the changes introduced in this PR but I want to make sure why this happens (and fix the issue) before merging the PR.

**Comment by idChef** [comment]
There is a variable which gets overwritten when applying custom background to a modal, `export let styleBg = { top: 0, left: 0 };` and since I set body's position to fixed it makes the modal cut off.  I just set `.bg` to have these properties by default in every case. Here's the demo: https://svelte.dev/repl/03d4b30556014a449b542194aab711f1?version=3.20.1

**Comment by flekschas** [comment]
Thanks for the fix! I found few other edge cases that caused trouble.

Can you give the changes a shot at: https://svelte.dev/repl/5535f3c2062e48d28c7f8e0c9f0c7f3f?version=3.20.1

If everything works we can merge the PR.

**Comment by idChef** [comment]
Went through it on my phone and desktop. I think everything is good!

**Comment by flekschas** [comment]
Thanks again for taking the stab at #28 and submitting up the PR! Much appreciated

**Comment by MentalGear** [comment]
Thanks for adding, but maybe you want to use a lib (https://github.com/willmcpo/body-scroll-lock) for a long term, tested, cross device solution instead of having to test and maintain this separately.

**Pull request merged**
