### PR TITLE
Update Modal.svelte

### PR DESCRIPTION
**Pull request by truongvan**
fix 'document is not defined'  on sveltekit.

### CODE REVIEW

**Comment by flekschas** [comment]
Thanks for this PR. How does `svelte.afterUpdate()` ensure that `disableScroll()` and `enableScroll()` is call at the very same time it's been right now when `open()` is called?

**Comment by truongvan** [comment]
When `open()` is called, `Component` will appear, then `disableScroll()` will be called. It takes under 10ms from creating  `Component` to calling ` disableScroll()` . If using `svelte.beforeUpdate()` it takes under 1ms.

**Comment by flekschas** [comment]
It sounds like `beforeUpdate()` makes more sense then or why did you choose `afterUpdate()`?

**Comment by truongvan** [comment]
The diffence of the loading time between `beforeUpdate()` and `afterUpdate()` is quite small. Besides, I want to make sure `Component` appears before locking scroll.

**Review by flekschas — APPROVED** [review]
Looks good! Thanks for the explanation and the PR!

**Pull request merged**
